swagger: "2.0"
info:
  description: This is the swagger file that describes the functionality of this api. To make a request, remove /ui and
   add the relevant path.
  version: "1.0.0"
  title: Fanale Research Insights Api
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /get/blog/{id}:
      get:
        operationId: handleInsightsRequests.getOneBlog
        tags:
          - insights
        summary: Retrieve information for a single blog post
        description: Retrieve information for a single blog post.
        parameters:
          - name: id
            in: path
            description: id for article
            type: string
            required: True
        responses:
          200:
            description: Successfully found article
            schema:
              type: array
              items:
                properties:
                  author:
                    type: string
                  id:
                    type: string
                  content:
                    type: string
                  title:
                    type: string
                  date:
                    type: string
                  description:
                    type: string
                  image:
                    type: string
                  tags:
                    type: string
                  views:
                    type: string

  /get/learn/{id}:
    get:
      operationId: handleInsightsRequests.getOneLearn
      tags:
      - insights
      summary: Retrieve information for a single learn article
      description: Retrieve information for a single learn article.
      parameters:
      - name: id
        in: path
        description: article id
        type: string
        required: True
      responses:
        200:
          description: Successfully found article
          schema:
            type: array
            items:
              properties:
                id:
                  type: string
                content:
                  type: string
                title:
                  type: string
                description:
                  type: string
                image:
                  type: string
                tags:
                  type: string

  /getall:
    get:
      operationId: handleInsightsRequests.getAllBlogs
      tags:
      - insights
      summary: Retrieve information for a all posts
      description: Retrieve information for all posts
      responses:
        200:
          description: Successfully found stock
          schema:
            type: array
            items:
              properties:
                author:
                  type: string
                id:
                  type: string
                content:
                  type: string
                title:
                  type: string
                date:
                  type: string
                description:
                  type: string
                image:
                  type: string
                tags:
                  type: string
                views:
                  type: string

  /getall/learn:
    get:
      operationId: handleInsightsRequests.getAllLearn
      tags:
      - insights
      summary: Retrieve information for all learns
      description: Retrieve information for all learns.
      parameters:
      - name: id
        in: path
        description: article id
        type: string
        required: True
      responses:
        200:
          description: Successfully found article
          schema:
            type: array
            items:
              properties:
                id:
                  type: string
                content:
                  type: string
                title:
                  type: string
                description:
                  type: string
                image:
                  type: string
                tags:
                  type: string


  /post/blog:
    post:
      operationId: handleInsightsRequests.postBlog
      tags:
      - insights
      summary: Retrieve information for a single blog post
      description: Retrieve information for a single blog post.
      consumes:
        - application/json
      parameters:
      - name: body
        in: body
        description: The blog to post.
        schema:
          type: object
          required:
            - content
          properties:
            author:
              type: string
            date:
              type: string
            title:
              type: string
            description:
              type: string
            content:
              type: string
            tags:
              type: string
            image:
              type: string
      responses:
        201:
          description: Successfully added blog

  /post/learn:
    post:
      operationId: handleInsightsRequests.postLearn
      tags:
      - learn
      summary: post information for a single learn post
      description: post information for a single learn post.
      consumes:
      - application/json
      parameters:
      - name: body
        in: body
        description: The blog to post.
        schema:
          type: object
          required:
          - content
          properties:
            title:
              type: string
            description:
              type: string
            content:
              type: string
            tags:
              type: string
            image:
              type: string
      responses:
        201:
          description: Successfully added blog





